stages:
  - test

tests:python:
  stage: test
  image: python:3
  services:
    - postgres:9
  variables:
    POSTGRES_DB: zoudb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mysecretpassword
    DB_HOST: postgres
  script:
    # Update
    - apt update
    - wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
    - dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
    - echo "deb http://www.deb-multimedia.org stretch main non-free" | tee -a /etc/apt/sources.list
    - apt update
    - apt install -y python-dev libpq-dev
    - apt install -y --force-yes ffmpeg

    # Install requirements
    - pip install -r requirements.txt

    # Run Tests
    - PYTHONPATH=. py.test
  tags:
    - test
